version: 2.1

jobs:
  test-env-var:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Parthasarathi"
          command: echo $MY_ENV_VAR

workflows:
  test-env-var-workflow:
    jobs:
      - test-env-var
